ARDUINO_LIBS = SPI SdFat SFEMP3Shield Ethernet 

BOARD_TAG         = ethernet
#BOARD_TAG         = uno

#ARDUINO_DIR  = /usr/share/arduino
#ARDMK_DIR    = /usr/share/arduino
PROJECT_DIR       = $(CURDIR)
USER_LIB_PATH    :=  $(PROJECT_DIR)/ulibs

ISP_PROG = avrispmkii
MONITOR_PORT  = /dev/ttyUSB0
CFLAGS_STD        = -std=gnu11
CXXFLAGS_STD      = -std=gnu++11
#CXXFLAGS         += -pedantic -Wall -Wextra

include /usr/share/arduino/Arduino.mk
