ARDUINO_LIBS = SPI SdFat SFEMP3Shield

BOARD_TAG         = atmega328
#BOARD_TAG         = uno

#ARDUINO_DIR  = /usr/share/arduino
#ARDMK_DIR    = /usr/share/arduino
PROJECT_DIR       = $(CURDIR)
USER_LIB_PATH    :=  $(PROJECT_DIR)/ulibs

MONITOR_PORT  = /dev/ttyACM0
CFLAGS_STD        = -std=gnu11
CXXFLAGS_STD      = -std=gnu++11
#CXXFLAGS         += -pedantic -Wall -Wextra

include /usr/share/arduino/Arduino.mk
